[package]
name = "gearly-order"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8", features = ["macros"] }
dotenvy = "0.15"
diesel = { version = "2.3.13", features = ["mysql"] }
deadpool-diesel = { version = "0.7.0", features = ["mysql"] }
serde = {version = "1.0.228", features = ["derive"]}
chrono = "0.4.45"
tokio = { version = "1.53.1", features = ["full"] }
jsonwebtoken = "11.1.0"
