-- Your SQL goes here
ALTER TABLE order_items
    ADD COLUMN id INT AUTO_INCREMENT PRIMARY KEY FIRST,
    CHANGE COLUMN PRICE unit_price INT NOT NULL,
    MODIFY COLUMN order_id INT NOT NULL,
    MODIFY COLUMN product_id INT NOT NULL,
    MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
